# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: azi
spec:
  host: multi-az-workshop-service
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
          - from: "eu-west-1/eu-west-1a/*"
            to:
              "eu-west-1/eu-west-1a/*": 100
          - from: "eu-west-1/eu-west-1b/*"
            to:
              "eu-west-1/eu-west-1b/*": 100
          - from: "eu-west-1/eu-west-1c/*"
            to:
              "eu-west-1/eu-west-1c/*": 100