# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: azi
spec:
  host: multi-az-workshop-service
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
          - from: "ap-southeast-2/ap-southeast-2a/*"
            to:
              "ap-southeast-2/ap-southeast-2a/*": 100
          - from: "ap-southeast-2/ap-southeast-2b/*"
            to:
              "ap-southeast-2/ap-southeast-2b/*": 100
          - from: "ap-southeast-2/ap-southeast-2c/*"
            to:
              "ap-southeast-2/ap-southeast-2c/*": 100